### ISSUE TITLE
Dataset tracking system

### ISSUE THREAD

**Issue by diazrenata** [PSInetRCN/organization#16]
Create a project board to track dataset movement through the long arc pipeline.

- [ ] RMD create a prototype and add a couple of datasets
- [ ] JG, AMR refine the board
- [ ] Group effort to populate board with the datasets we've already made
